<?php

/**
 * This is example code for a Drupal 4 to Drupal 7 migration. This won't actually
 * work without defining the referenced vocabularies, content types, and fields
 * on each side.
 */

/**
 * Implements hook_flush_caches().
 */
function migrate_trizones_flush_caches() {
  migrate_trizones_register_migrations();
}

/**
 * Register all D4->D7 migrations.
 */
function migrate_trizones_register_migrations() {
  /**
   * Each migration being registered takes an array of arguments, some required
   * and some optional. Start with the common arguments required by all - the
   * source_connection (connection key, set up in settings.php, pointing to
   * the Drupal 4 database) and source_version (major version of Drupal).
   */
  $common_arguments = array(
    'source_connection' => 'legacy',
    'source_version' => 4,
  );

  // The description and the migration machine name are also required arguments,
  // which will be unique for each migration you register.
  $arguments = $common_arguments + array(
    'description' => t('Migration of users from Drupal 4'),
    'machine_name' => 'TZUser',
  );

  // We just use the migrate_d2d D4 migration class as-is.
  Migration::registerMigration('TrizonesUserMigration', $arguments['machine_name'],
                               $arguments);

  // For vocabulary migrations, source_vocabulary and destination_vocabulary are
  // required arguments. Note that in Drupal 4 vocabularies did not have machine
  // names, so we use the vocabulary ID to uniquely identify them.
   $vocabulary_arguments = array(
    array(
      'description' => t('Migration of Forum terms from Drupal 4'),
      'machine_name' => 'TZForumTerms',
      'source_vocabulary' => '1', 
      'destination_vocabulary' => 'forums',
    ),
    array(
      'description' => t('Migration of Topics terms from Drupal 4'),
      'machine_name' => 'TZTopicTerms',
      'source_vocabulary' => '2',
      'destination_vocabulary' => 'topics',
    ),
    array(
      'description' => t('Migration of Race terms from Drupal 4'),
      'machine_name' => 'TZRaceTerms',
      'source_vocabulary' => '4',
      'destination_vocabulary' => 'races',
    ),
    array(
      'description' => t('Migration of Resource terms from Drupal 4'),
      'machine_name' => 'TZResourceTerms',
      'source_vocabulary' => '5', 
      'destination_vocabulary' => 'resource',
    ),
    array(
      'description' => t('Migration of Workout Tracks terms from Drupal 4'),
      'machine_name' => 'TZWorkoutTrackTerms',
      'source_vocabulary' => '6',
      'destination_vocabulary' => 'workout_tracks',
    ),
    array(
      'description' => t('Migration of Positions terms from Drupal 4'),
      'machine_name' => 'TZPositionTerms',
      'source_vocabulary' => '8',
      'destination_vocabulary' => 'positions',
    ),
    array(
      'description' => t('Migration of Apparal & Gear terms from Drupal 4'),
      'machine_name' => 'TZApparelGearTerms',
      'source_vocabulary' => '9',
      'destination_vocabulary' => 'apparel_and_gear',
    ),
    
    
   );

  // Again, we're using the migrate_d2d class directly.
  // The soft dependency says that while we don't have to run the user migration
  // first, we want to make sure it's listed first so the vocubularies are
  // listed right ahead of the node migrations.
  $common_vocabulary_arguments = $common_arguments + array(
    'class_name' => 'TrizonesTermMigration',
    'soft_dependencies' => array('TZUser'),
  );
  foreach ($vocabulary_arguments as $arguments) {
    $arguments += $common_vocabulary_arguments;
     echo "\nterm machine name: $arguments[machine_name]";
    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
                                 $arguments);
  }


  // Node migrations - each has its own class derived from the migrate_d2d class,
  // specifying its particular field mappings and transformations. source_type
  // and destination_type are required arguments.
   $node_arguments = array(
    array(
      'class_name' => 'Drupal4ForumMigration',
      'description' => t('Migration of forum nodes from Drupal 4'),
      'machine_name' => 'D4Forum',
      'source_type' => 'forum',
      'destination_type' => 'forum',
    ),
  );
  // Tell the node migrations where the users are coming from, so they can
  // set up the dependency and resolve D4->D7 uids.
  $common_node_arguments = $common_arguments + array(
    'user_migration' => 'TZUser',
  );
  foreach ($node_arguments as $arguments) {
    $arguments = array_merge_recursive($arguments, $common_node_arguments);
//    Migration::registerMigration($arguments['class_name'], $arguments['machine_name'],
//                                 $arguments);
  }
}


/**
 * Implements hook_migrate_api().
 */
function migrate_trizones_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}
